# Generated by Django 3.2.5 on 2021-07-12 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_rename_crate_date_answer_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='crate_date',
            new_name='create_date',
        ),
    ]
