# Generated by Django 3.2.5 on 2021-07-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20210719_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='modify_data',
            new_name='modify_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='modify_data',
            new_name='modify_date',
        ),
    ]
