# Generated by Django 3.2.5 on 2021-07-27 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0012_remove_question_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
