# Generated by Django 3.2.5 on 2021-07-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_answer_author'),
        ('pybo', '0013_delete_photo'),
    ]

    operations = [
    ]
